consider cards with frameEffects promos
Cockatrice/Cockatrice pull request #4097
Opened 2020-09-12 15:38 UTC by ebbit1q

## Related Ticket(s)
- https://github.com/Cockatrice/Cockatrice/pull/3965

## Short roundup of the initial problem
lotus cobra is shown as an alternative printing with fancy frame in cockatrice as number 307 because it does not have the isAlternative property set

note that for testing this you'd need to clear the image cache and restart cockatrice after running oracle

## What will change with this Pull Request?
- all cards with the frameEffects property will be treated like promos and will be deferred to be added later together with the promos
- if a special set contains only promos and alt frame versions the "non promo" alt frame versions are no longer given priority over the promo versions and either of them might become the selected printing for that set (in practice highest collector number takes precedence afaik)

## Screenshots

2020-09-13 21:12 UTC, ZeldaZach requested changes
This is incorrect, based on the values a frameEffect can have.
See https://mtgjson.com/data-models/card/ for more details, but some examples include "devoid" and "miracle", which are clearly fine examples that shouldn't be delegated away

2020-09-21 16:09 UTC, ebbit1q commented
I considered parsing the frameeffects but opted to instead have all cards that are not "promo" or something like it retain the first copy instead of parsing all of them and keeping the last.
This means that cards from unstable like Secret Base will now show the first iteration instead of the last and cards like lotus cobra in znr will keep the lower collectors number because that's the order in which they appear from mtgjson

2020-09-21 16:09 UTC, ebbit1q commented
see https://github.com/mtgjson/mtgjson/issues/679

2020-09-22 20:09 UTC, ZeldaZach approved these changes
This seems okay as a workaround for now. When we integrate V5, we should have better handling hopefully

2020-09-22 20:09 UTC, merged