Fix for #4284
Cockatrice/Cockatrice pull request #4347
Opened 2021-05-12 19:42 UTC by djpiper28

-> The menus have the update menu thing emitted when they get triggered.
| -> works surprising well https://youtu.be/KOOmhxvHA2c is a demo on a 10000ish card deck

## Related Ticket(s)
- Fixes #4284

## Short roundup of the initial problem
The client was slow when opening large decks for games or having large amounts of cards played. The bottleneck was the action menu being updated,

## What will change with this Pull Request?
- Made the menus update when they get triggered.

## Screenshots

2021-05-12 20:57 UTC, ebbit1q requested changes
this looks promising, while testing I noticed:

the menu for cards in play is suddenly used for cards on the stack

cards in views no longer have menus at all

2021-05-12 22:04 UTC, ebbit1q commented
also note that because this is so fast, there is no need anymore to limit the amount of menus as implemented here https://github.com/Cockatrice/Cockatrice/pull/4262

2021-05-13 00:30 UTC, ebbit1q requested changes
this now works great on all the cards not in views but all cards in views still do nothing

2021-05-13 00:34 UTC, ebbit1q requested changes
another problem is that all card actions are also bound to keybinds, if the action isn't initialised yet all keyboard actions on the card fail, a way to remedy this would be to initialise the menu when the card is interacted with in any way

2021-05-15 03:29 UTC, ebbit1q commented
ugh, I started looking into what is going on here and fixing things.

I found some bigger problems going on with card selection, expect me to push a change soon.

2021-05-15 17:02 UTC, ebbit1q commented
so this is a rather annoying bug that is related but not the focus of this pr, if this bug were fixed it would mean this pr would be finished.

however, it's not really the scope of this pr, I was thinking of making a separate ticket for it but I am worried that it might conflict with this change.

2021-05-16 10:58 UTC, djpiper28 commented
Does that still update shortcuts when the selected card is Zone moved?

2021-05-16 12:26 UTC, ebbit1q commented
yes, it technically also does if it is moved inside a zone

2021-05-28 23:59 UTC, ebbit1q commented
I made a ticket for it https://github.com/Cockatrice/Cockatrice/issues/4372

2021-06-02 02:02 UTC, ZeldaZach commented on cockatrice/src/player.cpp
> +    return aCardMenu->menu(); // can return nullptr
I don't like the removal of a NP check

2021-06-02 03:10 UTC, ebbit1q approved these changes

2021-06-02 03:14 UTC, ZeldaZach commented on cockatrice/src/player.cpp
> +    } else {
Can just revert this function to what it was, no need for else

2021-09-14 20:35 UTC, ZeldaZach approved these changes
Tested and good to go!

2021-09-14 20:35 UTC, merged