make cards on the stack slightly overlap to stress order
Cockatrice/Cockatrice pull request #4930
Opened 2023-10-31 17:14 UTC by ebbit1q

## Related Ticket(s)
- Fixes #4872

## Short roundup of the initial problem
the order of cards on the stack was difficult to understand

## What will change with this Pull Request?
- dragging cards to the stack now places the card at the location it is dropped
- cards on the stack will overlap by 1/3rd always

## Screenshots

![image](https://github.com/Cockatrice/Cockatrice/assets/36401181/f2ec1d06-4cb0-45f6-aeac-ba7b324ad93a)

2023-11-05 09:34 UTC, tooomm commented
Looking good. Very helpful 👍 
<img width="132" alt="image" src="https://github.com/Cockatrice/Cockatrice/assets/9874850/36b1f862-7362-4138-8002-9a3df6661c11">

2023-11-05 11:00 UTC, ebbit1q commented
if we'd like the overlap amount to be configurable I could add it to the settings, it is currently 1/3rd of a card height

2023-11-05 11:54 UTC, tooomm commented
Personally, I do not think that's needed.

I guess you tried other values like 1/4 or 1/5 as well, and decided 1/3 was the best?
The exact value should not matter too much as long as there is an overlap.

Probably smaller numbers are better than bigger - like 50% overlap even with only 2-3 cards on the stack would not be great.

2023-11-05 13:38 UTC, ebbit1q commented
I haven't tried other numbers

2023-11-12 18:35 UTC, tooomm reviewed
1/3 looks good to me

2023-11-16 18:07 UTC, ebbit1q commented
do we want to do the same with the vertical hand layout? they look strange next to each other.

2023-11-18 08:14 UTC, tooomm requested changes
Okok, you went for the settings option. 👍 
Changing it does not apply the new setting unless the zones are updated though.

I would also switch the wording in settings around to stress the stack option (always active) over the vertical cards one (optional).

2023-11-18 08:14 UTC, tooomm commented on cockatrice/src/dlg_settings.cpp
> +    verticalCardOverlapPercentLabel.setText(tr("Minimum overlap percentage of cards in vertical hand and stack"));
```suggestion
    verticalCardOverlapPercentLabel.setText(tr("Minimum overlap percentage of cards on the stack and in vertical hand"));
```

2023-12-10 10:35 UTC, tooomm commented
>Changing (the overlapping value) does not apply the new setting unless the zones are updated though.

Do you plan to address this @ebbit1q?

2023-12-10 13:22 UTC, ebbit1q commented
I tried but for some reason it doesn't work, I decided to remove the code for it again.

2023-12-10 14:08 UTC, tooomm approved these changes
We can list it as improvement and look into it later, otherwise we have another PR with enhancements waiting for months.

2023-12-15 18:59 UTC, ZeldaZach approved these changes

2023-12-15 19:00 UTC, merged