Code refractoring
Cockatrice/Cockatrice pull request #5118
Opened 2024-10-05 19:25 UTC by LunyaticCat

## Short roundup of the initial problem
All files are currently in the root directory, making it really hard for new devs to join the project.

## What will change with this Pull Request?
every cockatrice files are put into different folders matching what they do.

2024-10-05 19:50 UTC, BruebachL requested changes
LGTM, pending changes.

2024-10-05 19:50 UTC, BruebachL commented on cockatrice/src/card_database_parser/cockatrice_xml3.cpp
Maybe add another underscore for readability (e.g. cockatrice_xml_3.cpp)

2024-10-05 19:50 UTC, BruebachL commented on cockatrice/src/card_database_parser/cockatrice_xml4.cpp
Maybe add another underscore for readability (e.g. cockatrice_xml_3.cpp)

2024-10-05 19:50 UTC, BruebachL commented on cockatrice/src/dialogs/dlg_connect.cpp
Some unwanted changes to UI naming here.

2024-10-08 10:04 UTC, tooomm commented
Where does the 10k reduced lines come from?

2024-10-08 10:52 UTC, LunyaticCat commented
> Where does the 10k reduced lines come from?

probably from github thinking I deleted a file called "cardzone" and added a file called "card_zone" when I simply renamed and moved it like other files

2024-10-11 04:33 UTC, ZeldaZach commented
Can you remove the oracle/ translations as well?

2024-10-12 19:03 UTC, ZeldaZach commented
Can you resolve the merge conflicts?

2024-10-13 10:19 UTC, tooomm requested changes
Great, the list of changes is now somewhat manageable. Thanks.
I had a look and put some notes when skimming trough.

Others, if you want to look at the source repo and have a look at the new structure, check if something should be changed: https://github.com/LunyaticCat/Cockatrice/tree/code-refractoring

2024-10-13 10:19 UTC, tooomm commented on cockatrice/src/client/tabs/tab_supervisor.cpp
> +#include "server.h"
Not sure about this one

2024-10-13 11:41 UTC, LunyaticCat commented on cockatrice/src/dialogs/dlg_register.cpp
> +    setWindowTitle(tr("DlgRegister to server"));
Ah yes, refactoring must have changed it without me noticing ^^'

2024-10-13 12:38 UTC, tooomm commented
@LunyaticCat It's now only about the conflicts that need resolution 👍 

![image](https://github.com/user-attachments/assets/8e6d10ee-fc64-40bf-9d00-19016217f3a6)

2024-10-14 20:54 UTC, tooomm approved these changes
Thanks for resolving the conflicts! 👍 

Will defer to others to sanity check the actual naming and folder structure. @ZeldaZach @ebbit1q

2024-10-14 21:46 UTC, ZeldaZach approved these changes
If you can untrack the changes on the `.github` and `webclient` dirs, this is good to go

2024-10-20 00:18 UTC, ZeldaZach commented
Can you resolve conflicts one more time? Then I'll merge this through!

2024-10-20 12:46 UTC, LunyaticCat commented
> Can you resolve conflicts one more time? Then I'll merge this through!

ok I think I did it!

2024-10-20 14:11 UTC, merged