New printing selector
Cockatrice/Cockatrice pull request #5182
Opened 2024-11-19 15:27 UTC by BruebachL

## Related Tickets
- Closes #2411 

## Short roundup of the initial problem
In the current state, users can use individual printings (i.e. their printings are displayed to their opponent) but the selection is locked to the default printing.

## What will change with this Pull Request?
- Add a new PrintingSelectorWidget to the TabDeckEditor to allow users to add/remove specific printings from their deck.

## Screenshots
[Provisional]
Sorted alphabetically:
![image](https://github.com/user-attachments/assets/e0cc8475-e6d1-437a-a15c-f908d538dbb1)

Sorted by preference:
![image](https://github.com/user-attachments/assets/403436e1-acba-482e-b84e-dd66980a5dc7)

2024-11-20 02:22 UTC, ZeldaZach commented
Attempting to change a card that's in the sideboard doesn't have any impact.

Crashes randomly when cards are removed from deck.

2024-11-21 13:50 UTC, ZeldaZach requested changes

2024-11-21 13:50 UTC, ZeldaZach commented on cockatrice/src/client/tabs/tab_deck_editor.cpp
> +    selectPrinting = menu.addAction("Select Printing");
tr()

2024-11-21 13:50 UTC, ZeldaZach commented on cockatrice/src/client/tabs/tab_deck_editor.cpp
> +    QAction *selectPrinting = menu.addAction("Select Printing");
tr()

2024-11-21 13:50 UTC, ZeldaZach commented on cockatrice/src/client/tabs/tab_deck_editor.cpp
> +    qDebug() << cardName;
cleanup debugs

2024-11-21 13:50 UTC, ZeldaZach commented on cockatrice/src/client/tabs/tab_deck_editor.cpp
> +        return;
brackets

2024-11-21 13:50 UTC, ZeldaZach commented on cockatrice/src/client/tabs/tab_deck_editor.cpp
> +        return;
brackets

2024-11-21 14:03 UTC, BruebachL commented on cockatrice/src/client/ui/widgets/printing_selector/printing_selector.cpp
> +    sortToolBar = new QHBoxLayout();
No harm in it, afaik.

2024-11-27 17:30 UTC, Bugtracker319 commented
While in game, looking at the library results in cards being not ordered / ordered from top card to bottom card.
Checking or unchecking respective boxes does not change anything. Issue occurs both offline and online.

<img src="https://github.com/user-attachments/assets/a5d57805-f002-4c51-b1da-4eeb015b39b9" alt="on view library cards not orderable" width="380"/> <img src="https://github.com/user-attachments/assets/5bf5fbf3-eeda-4e0f-ae37-ee6e22f4adba" alt="on view library cards not orderable" width="380"/>


Client and OS version details as above.

2024-11-27 17:42 UTC, BruebachL commented
> Loading decks created prior to card-version-checking client change and trying to switch a card from main deck to sideboard or vice versa via double-click results in client crash.
> 
> Potentially relevant: Client Version: 2.10.0-custom([ac85b36](https://github.com/Cockatrice/Cockatrice/commit/ac85b36dbef5624126219cec8f6b7be78c28c9ff)) (2024-11-21) Client Operating System: Ubuntu 20.04.6 LTS **Qt Version: 5.12.8**

Can not reproduce, please include deck list.

2024-11-27 17:44 UTC, BruebachL commented
> While in game, looking at the library results in cards being not ordered / ordered from top card to bottom card. Checking or unchecking respective boxes does not change anything. Issue occurs both offline and online.
> 
> <img alt="on view library cards not orderable" width="380" src="https://private-user-images.githubusercontent.com/97046622/390510261-a5d57805-f002-4c51-b1da-4eeb015b39b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3Mjk1ODYsIm5iZiI6MTczMjcyOTI4NiwicGF0aCI6Ii85NzA0NjYyMi8zOTA1MTAyNjEtYTVkNTc4MDUtZjAwMi00YzUxLWIxZGEtNGVlYjAxNWIzOWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDE3NDEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2ZWU3OGQ4NjY0ODQxMTU1ZWMxMGI3N2IzYTEyZDI4YzY0MTZjOTEwZWMxMGJlOTE2OTZhNzk0NzJhNDI2M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oxH2CIJpzQZq7UPP3IJI7PKrp2wmfN6GLxsvFDrrJWQ"> <img alt="on view library cards not orderable" width="380" src="https://private-user-images.githubusercontent.com/97046622/390512326-5bf5fbf3-eeda-4e0f-ae37-ee6e22f4adba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3Mjk1ODYsIm5iZiI6MTczMjcyOTI4NiwicGF0aCI6Ii85NzA0NjYyMi8zOTA1MTIzMjYtNWJmNWZiZjMtZWVkYS00ZTBmLWFlMzctZWU2ZTIyZjRhZGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDE3NDEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3ODBjZmQxYmYzOWJkNjY2NmIxZTcyM2UxZDc5ODRkZmFmNGMxNTM2ZmU3M2YyOTdiNGYzMzVkYjEyNGQ5YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JXFOBL3NSKfRhL1U7pGi4e9lAt5ogaXtvLeubxeWdhk">
> 
> Client and OS version details as above.

Not locally reproducible for me, tested with providerId and non-providerId decks, library view and buttons work on both for me.

2024-11-27 17:49 UTC, ZeldaZach commented
@Bugtracker319 I've pushed a fix for both of the issues reported, let me know if that helps!

2024-11-27 17:51 UTC, Bugtracker319 commented
> > Loading decks created prior to card-version-checking client change and trying to switch a card from main deck to sideboard or vice versa via double-click results in client crash.
> > Potentially relevant: Client Version: 2.10.0-custom([ac85b36](https://github.com/Cockatrice/Cockatrice/commit/ac85b36dbef5624126219cec8f6b7be78c28c9ff)) (2024-11-21) Client Operating System: Ubuntu 20.04.6 LTS **Qt Version: 5.12.8**
> 
> Can not reproduce, please include deck list.

2024-11-27 18:14 UTC, Bugtracker319 commented
> > Loading decks created prior to card-version-checking client change and trying to switch a card from main deck to sideboard or vice versa via double-click results in client crash.
> > Potentially relevant: Client Version: 2.10.0-custom([ac85b36](https://github.com/Cockatrice/Cockatrice/commit/ac85b36dbef5624126219cec8f6b7be78c28c9ff)) (2024-11-21) Client Operating System: Ubuntu 20.04.6 LTS **Qt Version: 5.12.8**
> 
> Can not reproduce, please include deck list.

Two deck files attached, simply change ".txt" to ".cod" before using.
[EDH_LoranThirdPath_MonoWStaxCombo_TWLAlt_V6.txt](https://github.com/user-attachments/files/17938516/EDH_LoranThirdPath_MonoWStaxCombo_TWLAlt_V6.txt)
[EDH_Obeka_V10.txt](https://github.com/user-attachments/files/17938517/EDH_Obeka_V10.txt)

2024-12-01 17:24 UTC, ebbit1q commented
the range of the card size slider in the printing selector is too big, when I make it very small the buttons on the card become useless small and when it's just a bit smaller than the default size the fonts already start doing weird things (is their font size set as a float correctly?)
![image](https://github.com/user-attachments/assets/9093a52f-bc2d-4707-a51f-db2cdbab6d41)
![image](https://github.com/user-attachments/assets/77d0a4b8-3394-4085-8aea-35ac63e54749)

2024-12-01 17:26 UTC, ebbit1q commented
is the font size adjusted at all when card size changes?

2024-12-02 02:06 UTC, BruebachL commented
> the range of the card size slider in the printing selector is too big, when I make it very small the buttons on the card become useless small and when it's just a bit smaller than the default size the fonts already start doing weird things (is their font size set as a float correctly?) ![image](https://private-user-images.githubusercontent.com/36401181/391350703-9093a52f-bc2d-4707-a51f-db2cdbab6d41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMDQ3MTcsIm5iZiI6MTczMzEwNDQxNywicGF0aCI6Ii8zNjQwMTE4MS8zOTEzNTA3MDMtOTA5M2E1MmYtYmMyZC00NzA3LWE1MWYtZGIyY2RiYWI2ZDQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDAxNTMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhZWEzODA0ZTZhY2NkNTJlZmM0ZTQ1NGE4M2E0YTE5YWYzYWRkYTY1NTA1YjgwOTc1NWE2YWQ3ZDliNzI2ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.e9gps1iJA6vbPnVb2pskQmar6s0u-YZnFpxh5PeNtSM) ![image](https://private-user-images.githubusercontent.com/36401181/391350742-77d0a4b8-3394-4085-8aea-35ac63e54749.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMDQ3MTcsIm5iZiI6MTczMzEwNDQxNywicGF0aCI6Ii8zNjQwMTE4MS8zOTEzNTA3NDItNzdkMGE0YjgtMzM5NC00MDg1LThhZWEtMzVhYzYzZTU0NzQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDAxNTMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3MjU5NTRjYjE3ODlmNWRmZjk3NTNlNjQ5ZjhmNWE4ZjQ2ZWJmZjg5NGI4NTM3ODQ0OWM1MjEwZmQ5NWNmMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.u9NI5gqdH1YxJP4kgq5rCU3N6mPy763k9yOggLWpr6A)

It's because QLabels with WordWrap enabled are *weird* and we already sort of hack them to work. On resize, we recalculate their minimum width, using the fontmetrics that Qt gives us. However, these *shouldn't* exceed the image under normal conditions, because they happily will and that ruins the "cards in a grid" effect. So, we clamp them to the card width. Qt then doesn't know how to wordwrap a too-long word which leads to the clipping you see here.

2024-12-02 02:06 UTC, BruebachL commented
> is the font size adjusted at all when card size changes?

Addressed in [34bdae7](https://github.com/Cockatrice/Cockatrice/pull/5182/commits/34bdae7f77fbba594229d5be6bd300f728de5791)

2024-12-05 01:26 UTC, ebbit1q requested changes
the sorting option selected should be saved between restarts

I'd much prefer the default sorting option be "preference"

importing a deck from clipboard with multiple of the same card and then adding one more of that card results in all of that card being removed, preferably either all cards would be replaced with the selected printing or a new entry would be added with a copy with the selected printing
> reproduction steps:
>1. ctrl shift v to import from clipboard
>2. type 99 island into the field
> 3. right click the island in the decklist and select the printing selector
>4. add any island in the printing selector to the main deck
>5. the decklist is now only one island
  
using the card size slider doesn't seem to have any effect on the font size at all still

the previous card and next card buttons seem to always affect the deck list, contradicting eg the arrow keys up/down which do the same thing but will affect either the card list or the deck list depending on which was selected last (on a side note, it might be nice to use the unactive color to make this more clear to the user, unrelated to this pr) this isn't very obvious, either rename the buttons to next card in deck or have it work the same as the arrow up/down action

when adding a custom card that doesn't have a uuid the printing selector will not register it in its card counter

having two card entries with the same name in the same set seems to very much upset the printing selector, I have no idea what is going on with this.

please make sure your changes work with different combinations of custom sets, here is an example xml I used:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<cockatrice_carddatabase version="4">
  <sets>
    <set>
      <name>ISL</name>
      <longname>Islands et cetera</longname>
      <settype>Island</settype>
      <releasedate>2099-99-99</releasedate>
    </set>
  </sets>
  <cards>
    <card>
      <name>Island</name>
      <prop>
        <type>Basic Land — Island</type>
        <coloridentity>U</coloridentity>
        <maintype>Land</maintype>
        <cmc>0</cmc>
      </prop>
      <set>ISL</set>
    </card>
    <card>
      <name>Island</name>
      <text>Island is not actually an island.</text>
      <prop>
        <type>Is Land</type>
        <coloridentity>I</coloridentity>
        <maintype>Is</maintype>
        <cmc>0</cmc>
      </prop>
      <set>ISL</set>
    </card>
    <card>
      <name>Not an Island</name>
      <prop>
        <type>Land — Plains</type>
        <coloridentity>W</coloridentity>
        <maintype>Land</maintype>
        <cmc>0</cmc>
      </prop>
      <set num="three" uuid="island">ISL</set>
    </card>
  </cards>
</cockatrice_carddatabase>
```

2024-12-06 02:16 UTC, BruebachL commented
> when adding a custom card that doesn't have a uuid the printing selector will not register it in its card counter

This is correct. A card without a UUID is not a defined card (i.e. a specific card from a set) so the printing selector can not display it (since it only displays concrete printings/versions of cards).

> having two card entries with the same name in the same set seems to very much upset the printing selector, I have no idea what is going on with this.

The printing selector correctly displays the first two entries as belonging to the same card. This is correct, since they have the same name. They also belong to the same set but that is negligible when we look at the real issue:
They are not differentiated by UUID. Differentiation by UUID in the set entry is *mandatory* to use this feature and there is no way around that.

> please make sure your changes work with different combinations of custom sets, here is an example xml I used:
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <cockatrice_carddatabase version="4">
>   <sets>
>     <set>
>       <name>ISL</name>
>       <longname>Islands et cetera</longname>
>       <settype>Island</settype>
>       <releasedate>2099-99-99</releasedate>
>     </set>
>   </sets>
>   <cards>
>     <card>
>       <name>Island</name>
>       <prop>
>         <type>Basic Land — Island</type>
>         <coloridentity>U</coloridentity>
>         <maintype>Land</maintype>
>         <cmc>0</cmc>
>       </prop>
>       <set>ISL</set>
>     </card>
>     <card>
>       <name>Island</name>
>       <text>Island is not actually an island.</text>
>       <prop>
>         <type>Is Land</type>
>         <coloridentity>I</coloridentity>
>         <maintype>Is</maintype>
>         <cmc>0</cmc>
>       </prop>
>       <set>ISL</set>
>     </card>
>     <card>
>       <name>Not an Island</name>
>       <prop>
>         <type>Land — Plains</type>
>         <coloridentity>W</coloridentity>
>         <maintype>Land</maintype>
>         <cmc>0</cmc>
>       </prop>
>       <set num="three" uuid="island">ISL</set>
>     </card>
>   </cards>
> </cockatrice_carddatabase>
> ```

2024-12-06 02:18 UTC, BruebachL commented
![image](https://github.com/user-attachments/assets/17788b2a-d84e-4f49-a5b4-0a1b3c1e9ec8)

With 

    <card>
      <name>Island</name>
      <prop>
        <type>Basic Land — Island</type>
        <coloridentity>U</coloridentity>
        <maintype>Land</maintype>
        <cmc>0</cmc>
      </prop>
      <set uuid="island1">ISL</set>
    </card>
    <card>
      <name>Island</name>
      <text>Island is not actually an island.</text>
      <prop>
        <type>Is Land</type>
        <coloridentity>I</coloridentity>
        <maintype>Is</maintype>
        <cmc>0</cmc>
      </prop>
      <set uuid="island2">ISL</set>
    </card>

2024-12-13 21:15 UTC, ebbit1q commented
I tested this again today but for some reason the minus button in the printing selector stopped working for me?

2024-12-16 01:17 UTC, BruebachL commented
> I tested this again today but for some reason the minus button in the printing selector stopped working for me?

[aa91604](https://github.com/Cockatrice/Cockatrice/pull/5182/commits/aa91604f305d9acaaf8f1532e660faea769281ae) changed this because it now requires the card number to find the card in the deckModel. 

Fixed in [af38e63](https://github.com/Cockatrice/Cockatrice/pull/5182/commits/af38e632d90f888e0d5042248de2709bb905037c)

2024-12-19 01:55 UTC, ZeldaZach commented on cockatrice/src/client/ui/widgets/printing_selector/printing_selector.cpp
> +        QTimer::singleShot(100, this, &PrintingSelector::updateDisplay);
Move to showEvent

2024-12-19 02:14 UTC, ZeldaZach commented
Note: We need to support retranslateUi, but we can do that in a fast follow up.

2024-12-19 02:26 UTC, ZeldaZach approved these changes

2024-12-19 02:40 UTC, merged